---
functional:
   - Пользователь может зарегистрироваться на сайте и войти с помощью аккаунта GitHub
   - Пользователь может зарегистрироваться на сайте и войти с помощью аккаунта Discord
   - Пользователь может зарегистрироваться на сайте и войти с помощью логина и пароля
   - Должна быть возможность запустить пробную игру без регистрации
   - Пользователь может создать игру с другим случайным пользователем
   - Пользователь может создать игру с ботом
   - Пользователь может создать игру с выбранным оппонентом
   - В режиме игры каждый участник видит код своего соперника в онлайн режиме
   - Оба игрока видят и свой редактор и соперника
   - Каждый игрок имеет кнопку "отладки" для проверки своего решения с неограниченным числом попыток
   - Должна быть таблица рейтинга игроков с возможностью фильтрации
   - В личном кабинете пользователя доступна статистика по общему количеству игр, побед и используемым языкам программирования
   - Пользователь может создавать турниры
non-functional:
   - Сайт должен выдерживать большое количество трафика, например, 1000 одновременных пользователей
   - Должна быть мобильная версия сайта
   - Сайт должен обеспечивать безопасность и защиту данных пользователей
implicit:
   - Пользователи должны иметь статус "в сети" или "не в сети"
   - Рейтинг пользователя отображается рядом с аватаром
   - Боты должны быть отмечены пиктограммой бота
